"""initial

Revision ID: 5264331b4036
Revises: 
Create Date: 2026-06-12 01:54:52.154957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5264331b4036'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'datasets', ['name'])
    op.add_column('metrics', sa.Column('id_models', sa.Integer(), nullable=False))
    op.add_column('metrics', sa.Column('details', sa.TEXT(), nullable=True))
    op.create_foreign_key(None, 'metrics', 'models', ['id_models'], ['id_models'])
    op.add_column('metrics_results', sa.Column('value', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'models', ['name'])
    op.add_column('models_snapshots', sa.Column('folder_path', sa.String(), nullable=False))
    op.drop_column('models_snapshots', 'params_path')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.add_column('models_snapshots', sa.Column('params_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('models_snapshots', 'folder_path')
    op.drop_constraint(None, 'models', type_='unique')
    op.drop_column('metrics_results', 'value')
    op.drop_constraint(None, 'metrics', type_='foreignkey')
    op.drop_column('metrics', 'details')
    op.drop_column('metrics', 'id_models')
    op.drop_constraint(None, 'datasets', type_='unique')
    # ### end Alembic commands ###
